### PR TITLE
 Upgrade to ember-cli 3.6.0

### PR DESCRIPTION
**Pull request by FutoRicky**
- Fix tests
  - Update ember-github-pages
  - Add ember-cli-shims
  - set template according to very strict eslinter. Looks ugly in my opinion, but was the only way for the tests template linter to pass

### CODE REVIEW

**Comment by FutoRicky** [comment]
The only reason the travis build is failing is because it's looking for bower modules and not finding them, due to the fact that ember-cli 3+ stopped using bower.

**Comment by tsteuwer** [comment]
Will look at this after the holidays. Life's kinda busy atm. :D

**Comment by Houndsto0th** [comment]
What's the word on getting this merged in? I'd prefer to continue to use the main project over forking/using someone else's fork.

**Comment by tsteuwer** [comment]
@Houndsto0th @FutoRicky ,

Sorry about that. Life's been a bit hectic lately. I did test this branch and this PR only makes the initial page view event fire. Every other event does not fire and I'm trying to track down what's causing the problem. The logging code says that it sent the information but the Real-Time overview in GA and GA Debugger shows no events are being sent.

**Comment by tsteuwer** [comment]
Ok, this looks good. I'm guessing something was cached on my side as it just wasn't working. As soon as I changed a file it started working. Reverted the change and it began working. Going to finish a run through then this PR looks good. As far as the unit tests failing I'll remove the need for 2.x in the tests and this can live on as an Ember 3 addon. For previous versions they can use the 0.5.2 version.

**Comment by Houndsto0th** [comment]
Sounds great, one of the bigger deprecation concerns was the ember-cli-babel version

**Comment by tsteuwer** [comment]
@Houndsto0th why do you say that?

**Comment by tsteuwer** [comment]
Everything looks good. I'll fix Travis in another PR.

**Comment by tsteuwer** [comment]
Published in 1.0.0

**Pull request merged**
